// @ts-check
/**
 * Themed fortunes: 18 per charm, 108 total. Every line is a kindness, applies to
 * anyone, and never predicts something that can fail. The charm sets the mood;
 * the fortune makes it personal.
 *
 * Index order must match CHARMS in content.js: clover, star, fish, key, moon, acorn.
 */

/** @type {string[][]} */
export const THEMED_FORTUNES = [
  // 🍀 Clover — small luck that keeps showing up
  [
    "Small luck is following you around today. Let it.",
    "Something you've been carrying gets lighter today.",
    "A small kindness you did a while ago comes back around.",
    "Luck today looks like a good conversation.",
    "One thing goes smoother than expected. Enjoy it.",
    "You'll be right about something you were unsure of.",
    "An ordinary moment turns out to be the good part.",
    "Something small makes you laugh out loud.",
    "Good news travels toward you today.",
    "You'll find something you thought was lost.",
    "A little generosity comes back doubled.",
    "The next thing you try works.",
    "Today, you get to be the lucky coincidence.",
    "A stranger's good mood is contagious today. Catch it.",
    "The thing you're dreading is smaller than it looks from here.",
    "You'll notice something beautiful that everyone else walks past.",
    "You're about to be someone's good news.",
    "Somebody remembers your name for the right reason.",
  ],
  // ⭐ Star — a bright turn when you least expect it
  [
    "A bright turn is coming when you least expect it.",
    "Something you're proud of gets noticed today.",
    "You'll be surprised by how much you already know.",
    "A good idea arrives while you're doing something else.",
    "Someone learns something from watching you today.",
    "You're closer than the map suggests.",
    "The version of you that shows up today is the right one.",
    "Something you say lands exactly right.",
    "Today, your curiosity is the compass.",
    "You'll find the words when you need them.",
    "A little nerve today pays off for weeks.",
    "You'll be the calm one in the room.",
    "You'll remember today for a reason you can't guess yet.",
    "What you're growing is taking root, even if you can't see it.",
    "You'll finish the sentence someone else couldn't.",
    "Your timing is better than you think.",
    "Someone is glad you exist. They might even say so.",
    "A tiny yes leads somewhere interesting.",
  ],
  // 🐟 Fish — go with the current
  [
    "Go with the current today. It knows the way.",
    "What felt like a detour was the route.",
    "You're allowed to enjoy the easy part.",
    "Today rewards the first step, not the whole staircase.",
    "What you finish today will be enough.",
    "A little patience turns a no into a not-yet.",
    "The answer is closer to home than you think.",
    "Today, the shortcut is honesty.",
    "You are exactly on time.",
    "Let the day set the pace for once.",
    "The thing you can't control is handling itself.",
    "A plan you'd set aside gets a second wind.",
    "Your gut is right today. Trust it once.",
    "You'll get a second chance at a first impression.",
    "There's more room than you think. Take some.",
    "The thing you're looking forward to is looking forward to you.",
    "You'll leave a room better than you found it.",
    "Today's luck: a clear head and an easy heart.",
  ],
  // 🗝️ Key — something stuck comes loose
  [
    "Something that was stuck comes loose today.",
    "A door you thought was closed is only stuck.",
    "Today is a good day to ask.",
    "You've already done the hard part. Today is the reward.",
    "You'll spot the mistake before it matters.",
    "Something you fixed stays fixed.",
    "A small risk is the lucky move.",
    "The thing you've been avoiding takes ten minutes.",
    "You know what to do. You've known for a while.",
    "A conversation you've been putting off goes better than the one in your head.",
    "The lock was never the problem. You have the key.",
    "Something clicks today that didn't click yesterday.",
    "The first try counts more than you think.",
    "A problem you solved for someone else solves one of yours.",
    "Today, the next step is obvious once you take it.",
    "You'll be glad you said yes.",
    "The hard part is behind you. The good part is ahead.",
    "What you unlock today stays open.",
  ],
  // 🌙 Moon — quiet luck; rest counts
  [
    "Quiet luck today. Rest counts.",
    "Rest is a lucky move today.",
    "The pause you take today is not wasted.",
    "A quiet hour does more for you than a loud day.",
    "Today, being kind to yourself counts as progress.",
    "You don't have to earn tonight. It's already yours.",
    "Something you're worried about is already working out.",
    "Slow is a speed. Today it's the right one.",
    "What you let go of today makes room for something better.",
    "You'll sleep better than you expect tonight.",
    "A soft day is still a good day.",
    "The thing you need most today is the thing you keep skipping. Take it.",
    "Today, enough is enough. You've done enough.",
    "You're allowed to be tired and still be lucky.",
    "Someone is thinking well of you right now.",
    "A quiet good day counts the same as a loud one.",
    "You'll find a moment today that's just yours.",
    "The world keeps turning without your help. Let it, for an hour.",
  ],
  // 🌰 Acorn — a tiny start with big roots
  [
    "A tiny start today has big roots.",
    "The smallest thing you do today matters most.",
    "What you plant today, you'll thank yourself for later.",
    "Start small. It still counts.",
    "A habit you're building is further along than it feels.",
    "Something you began a while ago starts to show.",
    "Today, one honest step beats a perfect plan.",
    "You're building something. It's working.",
    "The seed doesn't know how tall it'll get. Neither do you. Keep going.",
    "A small promise kept today is a big one later.",
    "Something you thought was too late is right on time.",
    "What you're learning is sticking.",
    "The quiet work you've done is about to pay off.",
    "Today's small effort is tomorrow's easy day.",
    "Patience is doing something today. You just can't see it yet.",
    "You'll be proud of today later, even if it feels ordinary now.",
    "Roots first, then everything else. You're in the roots part.",
    "One good decision today grows into a dozen.",
  ],
];
